[package]
name = "rust-blockchain"
version = "0.1.0"
authors = ["Lalotai <hi@lalot.ai>"]
edition = "2018"

[dependencies]
docopt = "1.1"
serde = { version = "1.0", features = ["derive"] }
rand = "0.7"
serde_json = "1.0"
sha2 = "0.8"
config = "0.10"
lazy_static = "1.4"
rayon = "1.3.0"
hex = "0.4.2"
